import { BLOCKS, BLOCK_WEIGHTS, CHECK_LABELS, CRITERIA, GATES, GATE_LABELS, RULES_VERSION, STAGES, STAGE_LABELS, TRANSITION_CHECKS } from './constants';
import { assessmentInputSchema, ratingSchema, type AssessmentInput, type BlockId, type CheckId, type Evidence, type GateId, type Rating, type Stage } from './schema';
import { calculateCapacity, calculateEconomics } from './economics';
import { identifyOperationalSignals } from './comparison';
export function isReviewedEvidence(evidence:Evidence):boolean{return evidence.review?.status==='self_declared'&&!!evidence.review.author.trim()&&!!evidence.review.reviewedAt.trim()&&!!evidence.description.trim()&&!!evidence.claim.trim()&&!!evidence.source.trim()&&evidence.type!=='hypothesis';}
const reviewedLinks=(ids:readonly string[],evidence:readonly Evidence[])=>evidence.filter(e=>ids.includes(e.id)&&isReviewedEvidence(e));
const humanReview=(rating:Rating|AssessmentInput['checks'][CheckId])=>rating.review?.status==='self_declared'&&!!rating.review.author.trim()&&!!rating.review.reviewedAt.trim();
export interface ReviewedRating {score:number|null;submittedScore:number|null;evidenceIds:string[];reason:string|null;}
/** Scores are human declarations; metadata checks cannot authenticate the underlying claim. */
export function reviewRating(raw:Rating,evidence:readonly Evidence[]):ReviewedRating {
 const rating=ratingSchema.parse(raw);const links=reviewedLinks(rating.evidenceIds,evidence);let reason:string|null=null;
 if(rating.score===null)reason='N/D: nenhuma nota revisada registrada.';
 else if(!humanReview(rating)||!rating.justification.trim()||!rating.period.trim())reason='N/D: nota exige justificativa, período e revisão humana autodeclarada.';
 else if(links.length===0)reason='N/D: falta evidência vinculada e revisada; uma URL não comprova verificação.';
 else if(rating.evidenceIds.some(id=>!evidence.some(e=>e.id===id)))reason='N/D: referência de evidência inexistente.';
 else if(rating.score>0&&!links.some(e=>e.outcome==='supports'))reason='N/D: evidência desfavorável ou inconclusiva não sustenta nota positiva.';
 else if(rating.score===0&&!links.some(e=>e.outcome==='contradicts'))reason='N/D: zero exige evidência desfavorável explícita.';
 else if(rating.score>=4&&!links.some(e=>e.type==='observed_result'&&e.outcome==='supports'))reason='N/D: piloto demonstrado exige resultado observado favorável.';
 else if(rating.score===5&&(['cohort','period'] as const).some(dimension=>new Set(links.filter(e=>e.type==='observed_result'&&e.outcome==='supports'&&e[dimension].trim()).map(e=>e[dimension])).size<2))reason='N/D: replicação requer resultados favoráveis em coortes/períodos distintos.';
 return {score:reason?null:rating.score,submittedScore:rating.score,evidenceIds:links.map(e=>e.id),reason};
}
export interface ScorecardResult {coverage:number;partialIndex:number|null;completeIndex:number|null;label:string;weights:Readonly<Record<BlockId,number>>;}
export function calculateScorecard(scores:Record<BlockId,number|null>,weights:Readonly<Record<BlockId,number>>=BLOCK_WEIGHTS):ScorecardResult {
 if(Object.keys(weights).length!==BLOCKS.length||BLOCKS.some(id=>!Number.isFinite(weights[id])||weights[id]<=0)||Math.abs(BLOCKS.reduce((s,id)=>s+weights[id],0)-1)>1e-9)throw new Error('Pesos inválidos: seis pesos positivos devem somar 1.');
 for(const id of BLOCKS)if(scores[id]!==null&&(!Number.isInteger(scores[id])||scores[id]!<0||scores[id]!>5))throw new Error('Nota inválida: use inteiro de 0 a 5 ou null.');
 const known=BLOCKS.filter(id=>scores[id]!==null);const rawCoverage=known.reduce((sum,id)=>sum+weights[id],0);const coverage=Math.abs(rawCoverage-1)<1e-9?1:rawCoverage;
 const partialIndex=coverage>0?100*known.reduce((sum,id)=>sum+weights[id]*scores[id]!/5,0)/coverage:null;const completeIndex=coverage===1?partialIndex:null;
 return {coverage,partialIndex,completeIndex,label:coverage===1?'Índice completo':coverage>0?'Índice parcial dos blocos avaliados':'N/D — nenhum bloco avaliado',weights:{...weights}};
}
export type Recommendation='investigate'|'advance'|'review'|'iterate'|'pivot'|'pause'|'scale_gradually';
export const RECOMMENDATION_LABELS:Record<Recommendation,string>={investigate:'Investigar',advance:'Avançar para a próxima etapa',review:'Evidência insuficiente / revisão necessária',iterate:'Iterar',pivot:'Pivotar a cunha',pause:'Pausar',scale_gradually:'Escalar gradualmente'};
export interface Decision {recommendation:Recommendation;allowedStage:Stage;blocked:boolean;ruleCodes:string[];evidenceIds:string[];gaps:string[];conditions:string[];explanation:string;}
function assessedGate(input:AssessmentInput,id:GateId){const gate=input.gates[id];const links=reviewedLinks(gate.evidenceIds,input.evidence);return gate.status!=='pending'&&!(id==='structural_margin'&&gate.status==='confirmed'&&!gate.structuralAnalysisReviewed)&&gate.humanReviewed&&!!gate.justification.trim()&&!!gate.responsible.trim()&&!!gate.reviewedAt.trim()&&!!gate.reassessmentCondition.trim()&&links.length>0&&gate.evidenceIds.every(eid=>input.evidence.some(e=>e.id===eid))?gate.status:'pending';}
function assessedCheck(input:AssessmentInput,id:CheckId){const c=input.checks[id];if(!humanReview(c)||!c.justification.trim())return 'pending';if(c.status==='not_applicable')return id==='specialist'?'not_applicable':'pending';const links=reviewedLinks(c.evidenceIds,input.evidence);if(links.length===0||c.evidenceIds.some(eid=>!input.evidence.some(e=>e.id===eid)))return 'pending';if(c.status==='pass'&&!links.some(e=>e.outcome==='supports'))return 'pending';if(c.status==='fail'&&!links.some(e=>e.outcome==='contradicts'))return 'pending';return c.status;}
export function decide(input:AssessmentInput):Decision {
 const evidenceIds=new Set<string>();const base={allowedStage:input.stage,blocked:false,ruleCodes:[] as string[],evidenceIds:[] as string[],gaps:[] as string[],conditions:['Confirmação explícita do proprietário; a avaliação original permanece no histórico.']};
 const confirmed=GATES.filter(id=>assessedGate(input,id)==='confirmed');
 if(confirmed.length){confirmed.forEach(id=>input.gates[id].evidenceIds.forEach(e=>evidenceIds.add(e)));const pivot=confirmed.every(id=>id==='impossible_acceptance');return {...base,recommendation:pivot?'pivot':'pause',blocked:true,ruleCodes:confirmed.map(id=>`GATE_CONFIRMED_${id.toUpperCase()}`),evidenceIds:[...evidenceIds],gaps:confirmed.map(id=>GATE_LABELS[id]),conditions:confirmed.map(id=>input.gates[id].reassessmentCondition),explanation:`Porque há impedimento confirmado e revisado (${confirmed.map(id=>GATE_LABELS[id]).join(', ')} nas evidências ${[...evidenceIds].join(', ')}, a regra GATE_CONFIRMED bloqueia avanço e recomenda ${pivot?'pivotar a cunha':'pausar'}, independentemente do score.`};}
 if(input.stage==='idea')return {...base,recommendation:'investigate',allowedStage:'discovery',ruleCodes:['IDEA_SAFE_DISCOVERY'],gaps:['Investigar comprador, gasto atual, baseline, processo e cunha.'],conditions:['Somente pesquisa e redesenho seguros; não autoriza operação nem confirma viabilidade.'],explanation:'Porque o projeto está na etapa de ideia, a regra IDEA_SAFE_DISCOVERY recomenda descoberta; falta comprovar a oportunidade. Não há aprovação de viabilidade.'};
 const required=[...new Set(STAGES.slice(1,STAGES.indexOf(input.stage)+1).flatMap(stage=>[...TRANSITION_CHECKS[stage]]))] as CheckId[];
 const pendingGates=GATES.filter(id=>assessedGate(input,id)==='pending');const pendingChecks=required.filter(id=>assessedCheck(input,id)==='pending');const gaps=[...pendingGates.map(id=>`Revisar trava: ${GATE_LABELS[id]}.`),...pendingChecks.map(id=>`Comprovar: ${CHECK_LABELS[id]}.`)];
 required.forEach(id=>input.checks[id].evidenceIds.filter(eid=>input.evidence.some(e=>e.id===eid)).forEach(e=>evidenceIds.add(e)));GATES.forEach(id=>input.gates[id].evidenceIds.filter(eid=>input.evidence.some(e=>e.id===eid)).forEach(e=>evidenceIds.add(e)));
 const needsTargets=STAGES.indexOf(input.stage)>=STAGES.indexOf('contract');
 if(needsTargets&&(!input.pilotTargets||!input.pilotTargets.justification.trim()||(input.pilotTargets.pilotStartedAt!==null&&input.pilotTargets.declaredAt>=input.pilotTargets.pilotStartedAt)))gaps.push('Declarar metas de erro, margem, prazo e capacidade antes do início do piloto.');
 if(input.pricing.model==='financial_impact'&&['baseline','attribution','window','contestation'].some(key=>!input.pricing[key as 'baseline'|'attribution'|'window'|'contestation'].trim()))gaps.push('Preço por impacto exige baseline, atribuição, janela e contestação.');
 const needsScale=input.stage==='repetition'||input.stage==='scale_decision';
 if(needsScale){for(const id of ['repeated_demand','repeated_quality','sustainable_economics'] as const){const links=reviewedLinks(input.checks[id].evidenceIds,input.evidence).filter(e=>e.type==='observed_result'&&e.outcome==='supports');if((['cohort','period'] as const).some(dimension=>new Set(links.filter(e=>e[dimension].trim()).map(e=>e[dimension])).size<2))gaps.push(`Replicação em clientes/coortes e períodos distintos: ${CHECK_LABELS[id]}.`);}}
 const needsOperation=STAGES.indexOf(input.stage)>=STAGES.indexOf('paid_pilot');let capacityInsufficient=false;let economicsFailed=false;
 if(needsOperation){if(!input.economics)gaps.push('Economia do período/coorte não registrada.');else {const economics=calculateEconomics(input.economics);gaps.push(...economics.errors,...economics.gaps);if(economics.deliveryMargin!==null&&((input.pilotTargets&&economics.deliveryMargin<input.pilotTargets.marginMin)||(needsScale&&economics.deliveryMargin<=0)))economicsFailed=true;if(input.economics.receivedRevenueCents===0)gaps.push('Pagamento não observado na economia registrada.');}
 if(!input.capacity)gaps.push('Capacidade humana não registrada.');else {if(input.economics&&input.economics.period!==input.capacity.period)gaps.push('Períodos de economia e capacidade incompatíveis.');capacityInsufficient=!calculateCapacity(input.capacity).sufficient;if(input.pilotTargets&&calculateCapacity(input.capacity).requiredHours>input.pilotTargets.capacityHoursMax)capacityInsufficient=true;}}
 if(gaps.length)return {...base,recommendation:'review',blocked:true,ruleCodes:['CRITICAL_EVIDENCE_MISSING'],evidenceIds:[...evidenceIds],gaps,conditions:['Resolver pendências críticas com evidências e revisão humana. Pesquisa e redesenho seguros podem continuar.'],explanation:`Porque faltam ${gaps.length} condição(ões) obrigatória(s) revisada(s), a regra CRITICAL_EVIDENCE_MISSING recomenda revisão e mantém ${STAGE_LABELS[input.stage]}; falta comprovar: ${gaps.join(' ')}`};
 const failed=required.filter(id=>assessedCheck(input,id)==='fail');
 if(failed.length||capacityInsufficient||economicsFailed){const pivot=failed.some(id=>(id==='acceptance'||id==='price')&&input.checks[id].pivotSupported);return {...base,recommendation:pivot?'pivot':'iterate',blocked:true,ruleCodes:[pivot?'TEST_FAILED_PIVOT':'TEST_FAILED_ITERATE',...(capacityInsufficient?['HUMAN_CAPACITY_INSUFFICIENT']:[]),...(economicsFailed?['DECLARED_MARGIN_TARGET_NOT_MET']:[])],evidenceIds:[...evidenceIds],gaps:[...failed.map(id=>`Teste falhou: ${CHECK_LABELS[id]}.`),...(capacityInsufficient?['Capacidade humana insuficiente para o volume ou acima da meta declarada.']:[]),...(economicsFailed?['Margem da coorte abaixo da meta previamente declarada; não comprova inviabilidade estrutural.']:[])],conditions:['Ajustar configuração, registrar novo teste e reavaliar; não operar acima da capacidade.'],explanation:`Porque um teste obrigatório ou a capacidade/economia falhou nas evidências ${[...evidenceIds].join(', ')}, a regra ${pivot?'TEST_FAILED_PIVOT':'TEST_FAILED_ITERATE'} recomenda ${pivot?'pivotar a cunha':'iterar'}; falta demonstrar o atendimento das condições obrigatórias.`};}
 const scale=input.stage==='repetition'||input.stage==='scale_decision';const allowedStage=scale?'scale_decision':STAGES[STAGES.indexOf(input.stage)+1];
 return {...base,recommendation:scale?'scale_gradually':'advance',allowedStage,ruleCodes:[scale?'REPEATED_EVIDENCE_GRADUAL_SCALE':`TRANSITION_${input.stage.toUpperCase()}_TO_${allowedStage.toUpperCase()}`],evidenceIds:[...evidenceIds],conditions:[...base.conditions,'Manter direitos, controles e metas; reavaliar com nova coorte ou alteração material.'],explanation:`Porque as condições obrigatórias de ${STAGE_LABELS[input.stage]} estão revisadas nas evidências ${[...evidenceIds].join(', ')}, a regra ${scale?'REPEATED_EVIDENCE_GRADUAL_SCALE':'STAGE_REQUIRED_EVIDENCE'} recomenda ${scale?'escala gradual':STAGE_LABELS[allowedStage]}. O score não autoriza a transição; falta a confirmação do proprietário.`};
}
export function evaluateAssessment(raw:AssessmentInput){const input=assessmentInputSchema.parse(raw);const criteria=Object.fromEntries(CRITERIA.map(id=>[id,reviewRating(input.criteria[id],input.evidence)])) as Record<(typeof CRITERIA)[number],ReviewedRating>;const blocks=Object.fromEntries(BLOCKS.map(id=>[id,reviewRating(input.blocks[id],input.evidence)])) as Record<BlockId,ReviewedRating>;const scores=Object.fromEntries(BLOCKS.map(id=>[id,blocks[id].score])) as Record<BlockId,number|null>;return {rulesVersion:RULES_VERSION,operationalSignals:identifyOperationalSignals(input),decision:decide(input),scorecard:calculateScorecard(scores),criteria,blocks,economics:input.economics?calculateEconomics(input.economics):null,capacity:input.capacity?calculateCapacity(input.capacity):null,warnings:['Revisões do proprietário são autodeclaradas, não auditoria independente.','Confiança é declaração separada e não altera a nota.','Critérios e blocos têm notas independentes; não há equivalência automática.',...Object.values(criteria).filter(x=>x.submittedScore!==null&&x.score===null).map(x=>x.reason!),...Object.values(blocks).filter(x=>x.submittedScore!==null&&x.score===null).map(x=>x.reason!)]};}
export type AssessmentResult=ReturnType<typeof evaluateAssessment>;
