import { useState } from 'react';
import Link from '@/components/navigation';
import { useRouter } from '@/components/navigation';
import { SiteHeader, Footer } from '@/components/site-header';
import { Field } from '@/components/form-fields';
import { createBrowserClient } from '@/lib/supabase/client';

export default function AccountPage(){const router=useRouter();const [mode,setMode]=useState<'login'|'signup'|'reset'>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const client=createBrowserClient();
const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!client)return;setBusy(true);setError('');setNotice('');try{if(mode==='reset'){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/conta/redefinir`});if(error)throw error;setNotice('Se o endereço estiver cadastrado, você receberá instruções de recuperação.');}else if(mode==='signup'){const {data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/projetos`}});if(error)throw error;if(data.session)router.push('/projetos');else setNotice('Solicitação registrada. Confira seu e-mail para confirmar o cadastro.');}else{const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;router.push('/projetos')}}catch(e){setError(e instanceof Error?e.message:'Não foi possível autenticar. Tente novamente.')}finally{setBusy(false)}};
return <><SiteHeader compact/><main id="conteudo" className="auth-main"><div className="eyebrow dark-eyebrow">SEU ESPAÇO DE TRABALHO</div><h1>Projetos privados.<br/>Decisões rastreáveis.</h1><p>Entre para salvar rascunhos, registrar evidências e acompanhar a evolução das avaliações.</p>{!client?<div className="panel"><div className="helper-box warning-box"><strong>O modo privado ainda não está configurado neste ambiente.</strong><br/>Não é possível criar conta nem acessar projetos privados até a autenticação estar disponível.</div><Link className="button button-dark" href="/demo">Explorar demonstração sintética →</Link></div>:<section className="panel"><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('');setNotice('')}}>Entrar</button><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('');setNotice('')}}>Criar conta</button></div><form onSubmit={submit}><Field label="E-mail" type="email" value={email} onChange={setEmail} required/>{mode!=='reset'&&<label className="field"><span>Senha</span><input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/>{mode==='signup'&&<small>Use ao menos 8 caracteres e uma senha exclusiva.</small>}</label>}{error&&<div className="error-box" role="alert">{error}</div>}{notice&&<div className="success-box" role="status">{notice}</div>}<button className="button button-dark" style={{width:'100%'}} type="submit" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar nos meus projetos':mode==='signup'?'Criar conta privada':'Enviar recuperação'}</button>{mode==='login'&&<button type="button" className="text-link" style={{background:'none',marginTop:18}} onClick={()=>setMode('reset')}>Esqueci minha senha</button>}</form><p className="help-text" style={{marginTop:20}}>Os projetos ficam vinculados à sua conta. O código aberto e a demonstração não incluem seus dados privados.</p></section>}<p className="help-text"><Link href="/metodologia">Conheça o método, as limitações e a política de dados →</Link></p></main><Footer/></>}
