import { useEffect, useState } from 'react';
import { useRouter } from '@/components/navigation';
import Link from '@/components/navigation';
import { SiteHeader } from '@/components/site-header';
import { Workbench } from '@/components/workbench';
import { privateApi } from '@/components/private-api';
import { createBrowserClient } from '@/lib/supabase/client';
import { createEmptyAssessment, assessmentInputSchema, type AssessmentInput, type Stage } from '@/domain/framework/schema';
import type { AssessmentSnapshot } from '@/domain/framework/snapshots';
import type { AnalysisResult } from '@/lib/ai';

type Project={id:string;name:string;stage:Stage;draft:AssessmentInput|null};type Bundle={project:Project;assessments:Array<{snapshot:AssessmentSnapshot}>};
export default function PrivateProjectPage({id}:{id:string}){const router=useRouter();const [bundle,setBundle]=useState<Bundle|null>(null);const [author,setAuthor]=useState('');const [error,setError]=useState('');useEffect(()=>{const client=createBrowserClient();if(!client){queueMicrotask(()=>setError('O modo privado não está configurado neste ambiente.'));return;}void client.auth.getSession().then(async({data})=>{if(!data.session){router.replace('/conta');return}setAuthor(data.session.user.email||data.session.user.id);try{const r=await privateApi<Bundle>(`/api/projects/${id}`);r.project.draft=r.project.draft?assessmentInputSchema.parse(r.project.draft):createEmptyAssessment(id,r.project.stage);setBundle(r)}catch(e){setError(e instanceof Error?e.message:'Não foi possível acessar este projeto.')}})},[id,router]);return <><SiteHeader compact/>{error?<main id="conteudo" className="loading-state"><div className="error-box" role="alert">{error}</div><Link className="button button-light" href="/projetos">Voltar aos projetos</Link></main>:bundle?<Workbench initial={bundle.project.draft!} initialName={bundle.project.name} initialHistory={bundle.assessments.map(a=>a.snapshot)} author={author} demo={false} onSave={async(name,draft)=>{await privateApi(`/api/projects/${id}`,'PUT',{name,stage:draft.stage,draft});}} onAssess={async draft=>{const r=await privateApi<{assessment:{snapshot:AssessmentSnapshot}}>(`/api/projects/${id}/assessments`,'POST',{draft});return r.assessment.snapshot;}} onDelete={async()=>{await privateApi(`/api/projects/${id}`,'DELETE');router.replace('/projetos')}} onAssist={(evidenceIds,consent)=>privateApi<AnalysisResult>('/api/analysis','POST',{projectId:id,evidenceIds,consent})}/>:<main id="conteudo" className="loading-state"><span className="spinner"/><p>Abrindo projeto privado…</p></main>}</>}
