import { useEffect, useState } from 'react';
import Link from '@/components/navigation';
import { useRouter } from '@/components/navigation';
import { SiteHeader, Footer } from '@/components/site-header';
import { Field } from '@/components/form-fields';
import { privateApi } from '@/components/private-api';
import { createBrowserClient } from '@/lib/supabase/client';
import { STAGE_LABELS } from '@/domain/framework/constants';
import type { Stage } from '@/domain/framework/schema';

type Project={id:string;name:string;stage:Stage;updated_at:string};
export default function ProjectsPage(){const router=useRouter();const [projects,setProjects]=useState<Project[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [configured,setConfigured]=useState(true);const [creating,setCreating]=useState(false);const [name,setName]=useState('');const [busy,setBusy]=useState(false);
useEffect(()=>{const client=createBrowserClient();if(!client){queueMicrotask(()=>{setConfigured(false);setLoading(false)});return;}void client.auth.getSession().then(async({data})=>{if(!data.session){router.replace('/conta');return;}try{const r=await privateApi<{projects:Project[]}>('/api/projects');setProjects(r.projects)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar seus projetos.')}finally{setLoading(false)}});},[router]);
const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await privateApi<{project:Project}>('/api/projects','POST',{name:name.trim()||'Minha nova ideia',stage:'idea'});router.push(`/projetos/${r.project.id}`)}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar o projeto.');setBusy(false)}};
return <><SiteHeader compact/><main id="conteudo" className="projects-main"><div className="workspace-heading"><div><div className="eyebrow dark-eyebrow">ESPAÇO PRIVADO</div><h1>Meus projetos</h1><p>Organize o que sabe. Teste o que falta.</p></div>{configured&&<div className="button-row" style={{margin:0,gap:12}}><button className="button button-dark" onClick={()=>setCreating(!creating)}>{creating?'Fechar formulário':'+ Novo projeto'}</button><button className="text-link" style={{background:'none'}} onClick={async()=>{await createBrowserClient()?.auth.signOut();router.replace('/conta')}}>Sair</button></div>}</div>{!configured?<div className="panel"><h2 className="subheading" style={{marginTop:0}}>Modo privado indisponível neste ambiente</h2><p className="help-text">A autenticação e o banco privado precisam estar configurados. Nenhum projeto privado será salvo no navegador como alternativa.</p><Link className="button button-dark" href="/demo">Explorar demonstração →</Link></div>:<>{error&&<div className="error-box" role="alert">{error}</div>}{creating&&<form className="panel" onSubmit={create}><h2 className="subheading" style={{marginTop:0}}>Vamos organizar sua ideia.</h2><p>Você vai responder por escolhas. Se ainda não souber algo, pode deixar para depois.</p><Field label="Nome do novo projeto (opcional)" value={name} onChange={v=>setName(v.slice(0,120))} placeholder="Você pode escolher um nome depois"/><button className="button button-dark" disabled={busy} style={{marginTop:20}}>{busy?'Criando…':'Começar o guia'}</button></form>}{loading?<div className="loading-state"><span className="spinner"/><p>Carregando seus projetos…</p></div>:projects.length?<div className="projects-grid">{projects.map(p=><Link className="project-card" href={`/projetos/${p.id}`} key={p.id}><div><span className="pill pill-neutral">{STAGE_LABELS[p.stage]}</span><h2>{p.name}</h2><p>Atualizado em {new Date(p.updated_at).toLocaleDateString('pt-BR')}</p></div><span className="text-link">Continuar projeto <span>↗</span></span></Link>)}</div>:!error&&<div className="empty-state"><strong>Uma oportunidade começa com uma pergunta.</strong><p>Conte para quem é sua ideia e o que você quer melhorar. Vamos ajudar a escolher o próximo passo.</p><button className="button button-dark" onClick={()=>setCreating(true)}>Criar meu primeiro projeto</button></div>}</>}</main><Footer/></>}
