import type { Evidence, Rating } from '@/domain/framework/schema';

export function Field({label,value,onChange,help,multiline=false,type='text',placeholder='',required=false}:{label:string;value:string;onChange:(v:string)=>void;help?:string;multiline?:boolean;type?:string;placeholder?:string;required?:boolean}) {return <label className="field"><span>{label}</span>{multiline?<textarea aria-label={label} value={value} onChange={e=>onChange(e.target.value)} maxLength={5000} placeholder={placeholder} required={required}/>:<input aria-label={label} type={type} value={value} onChange={e=>onChange(e.target.value)} maxLength={type==='text'?5000:undefined} placeholder={placeholder} required={required}/>} {help&&<small>{help}</small>}</label>;}
export function NumberField({label,value,onChange,help,min=0,max,step=1}:{label:string;value:number|null;onChange:(v:number|null)=>void;help?:string;min?:number;max?:number;step?:number}) {return <label className="field"><span>{label}</span><input aria-label={label} type="number" value={value??''} min={min} max={max} step={step} placeholder="N/D" onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/>{help&&<small>{help}</small>}</label>;}
export function SelectField<T extends string>({label,value,onChange,options,help}:{label:string;value:T;onChange:(v:T)=>void;options:ReadonlyArray<{value:T;label:string}>;help?:string}){return <label className="field"><span>{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value as T)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>{help&&<small>{help}</small>}</label>;}
export function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}) {return <label className="checkbox-line"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;}
export function EvidencePicker({evidence,value,onChange}:{evidence:Evidence[];value:string[];onChange:(ids:string[])=>void}){return <div className="field"><span>Evidências vinculadas</span><div className="evidence-ref">{evidence.length?evidence.map(e=><Toggle key={e.id} label={`${e.id} — ${e.source||'Fonte não informada'} (${e.review?.status==='self_declared'?'autodeclarada':'pendente'})`} value={value.includes(e.id)} onChange={checked=>onChange(checked?[...value,e.id]:value.filter(id=>id!==e.id))}/>):<p>Registre uma evidência na etapa Evidências para vinculá-la aqui.</p>}</div></div>;}
export function ReviewFields({value,onChange}:{value:Rating['review'];onChange:(review:Rating['review'])=>void}) {return <div className="helper-box"><Toggle label="Revisei este registro como proprietário (revisão autodeclarada)" value={value?.status==='self_declared'} onChange={checked=>onChange(checked?{status:'self_declared',author:'',reviewedAt:new Date().toISOString()}:null)}/>{value&&<div className="form-grid" style={{marginTop:10}}><Field label="Autor da revisão" value={value.author} onChange={author=>onChange({...value,author})} help="Informe o responsável. Não é auditoria independente."/><Field label="Data da revisão" value={value.reviewedAt.slice(0,10)} type="date" onChange={date=>onChange({...value,reviewedAt:date?`${date}T12:00:00.000Z`:''})}/></div>}</div>;}
export function RatingForm({value,onChange,evidence}:{value:Rating;onChange:(r:Rating)=>void;evidence:Evidence[]}) { const set=<K extends keyof Rating>(key:K,v:Rating[K])=>onChange({...value,[key]:v});return <><div className="form-grid"><SelectField label="Nota proposta" value={value.score===null?'nd':String(value.score)} onChange={v=>set('score',v==='nd'?null:Number(v))} options={[{value:'nd',label:'N/D — ausência de dado'},{value:'0',label:'0 — evidência desfavorável'},{value:'1',label:'1 — muito fraca'},{value:'2',label:'2 — indício inicial'},{value:'3',label:'3 — hipótese parcialmente testada'},{value:'4',label:'4 — piloto demonstrado'},{value:'5',label:'5 — replicação entre clientes e períodos'}]}/><Field label="Período avaliado" value={value.period} onChange={v=>set('period',v)}/><Field label="Justificativa da nota" value={value.justification} onChange={v=>set('justification',v)} multiline/><Field label="Próximo teste" value={value.nextTest} onChange={v=>set('nextTest',v)} multiline/><SelectField label="Confiança (separada da nota)" value={value.confidence} onChange={v=>set('confidence',v)} options={[{value:'not_assessed',label:'Não avaliada'},{value:'low',label:'Baixa'},{value:'medium',label:'Média'},{value:'high',label:'Alta'}]}/><Field label="Fundamento da confiança" value={value.confidenceReason} onChange={v=>set('confidenceReason',v)}/></div><div style={{marginTop:18}}><EvidencePicker evidence={evidence} value={value.evidenceIds} onChange={v=>set('evidenceIds',v)}/></div><ReviewFields value={value.review} onChange={v=>set('review',v)}/></>;}
