import { createEmptyAssessment, type AssessmentInput, type Evidence, type EconomicsInput } from '@/domain/framework/schema';
import { COST_CATEGORIES } from '@/domain/framework/constants';

export const DEMO_STORAGE_KEY = 'radar-oaas.synthetic-demo.v1';
export const demoExamples = [
  { id: 'reconciliation', name: 'Conciliação financeira', subtitle: 'Uma entrega verificável para equipes financeiras' },
  { id: 'nda', name: 'Preparação de NDA', subtitle: 'Rascunho para revisão profissional obrigatória' },
  { id: 'provisioning', name: 'Provisionamento de usuários', subtitle: 'Acessos delimitados, reversíveis e revisados' },
] as const;
export function exampleEconomics(rate = 80): EconomicsInput {
  return { currency: 'BRL', period: '2026-09', cohort: 'Coorte didática', unit: 'resultado aceito', completed: 10, accepted: 10, humanHours: 12, hourlyRateCents: rate * 100, recognizedRevenueCents: 200000, receivedRevenueCents: 200000, onboardingAllocatedCents: 0, acquisitionAllocatedCents: 0, allocationExplanation: 'Exemplo aritmético sintético: onboarding e aquisição explicitamente zero neste exercício. Outros custos de R$ 240 classificados em infraestrutura, sem duplicação.', costs: COST_CATEGORIES.map(category => ({ id: `cost-${category}`, category, amountCents: category === 'ai' ? 30000 : category === 'human' ? 12 * rate * 100 : category === 'infrastructure' ? 24000 : 0, allocationKey: `synthetic-${category}`, allocationNote: 'Categoria separada; zero significa premissa explícita apenas deste exemplo didático.', currency: 'BRL', period: '2026-09', cohort: 'Coorte didática', unit: 'resultado aceito' })) };
}
export function createDemoAssessment(example: string = 'reconciliation'): AssessmentInput {
  const a = createEmptyAssessment(`synthetic-${example}`, 'discovery');
  a.canvas = { ...a.canvas, icp: 'Pequenos escritórios contábeis — hipótese sintética', sector: 'Serviços contábeis', geography: 'Brasil — jurisdição a revisar', buyer: 'Responsável financeiro do escritório', signer: 'Sócio responsável', payer: 'Escritório contábil', receiver: 'Analista financeiro', validator: 'Responsável financeiro', current_alternative: 'Comparação manual de extratos e lançamentos', narrow_work: 'Identificar divergências entre extrato e livro de uma conta bancária', trigger: 'Recebimento autorizado dos dois arquivos do período', inputs: 'Extrato e livro em formato estruturado; somente dados sintéticos nesta demonstração', outcome: 'Lista reconciliada de lançamentos e fila de divergências', acceptance: 'Totais conferem com as entradas; divergências têm referência rastreável', exceptions: 'Arquivo incompleto ou divergência ambígua encaminhada ao responsável humano', value: 'Hipótese: diminuir tempo de comparação sem perder rastreabilidade', distribution: 'Hipótese: parceria com escritórios contábeis', frequency: 'Mensal — hipótese', volume: '100 casos por período — cenário didático', proven_spend: '', decision_maker: 'Sócio responsável — identidade ainda não comprovada', baseline: 'A medir: horas, erros e prazo do processo atual', human_owner: 'Responsável da demonstração (fictício)', deadline: '2 dias úteis — hipótese a testar', price: 'A validar com comprador' };
  const e: Evidence = {id:'demo-evidence-01',type:'founder_statement',source:'Roteiro fictício da demonstração',date:'2026-09-23',period:'Exploração inicial sintética',cohort:'Exemplo de conciliação',description:'Um interlocutor fictício descreveu a comparação manual de extratos como uma tarefa recorrente. Este registro foi criado somente para demonstrar o produto.',claim:'Existe uma hipótese de trabalho estreito e recorrente a investigar.',url:'',outcome:'supports',review:{status:'self_declared',author:'Responsável fictício',reviewedAt:'2026-09-23T12:00:00.000Z'}};
  a.evidence=[e];
  a.criteria.valuable_pain={score:2,justification:'Indício inicial inteiramente sintético. Frequência e custo ainda precisam ser medidos.',evidenceIds:[e.id],period:e.period,nextTest:'Entrevistar compradores e medir o processo atual.',confidence:'low',confidenceReason:'Há somente um relato fictício de demonstração.',review:e.review};
  a.economics=exampleEconomics();
  a.capacity={period:'2026-09',cases:100,exceptionRate:0.2,reviewMinutesPerException:12,otherOperationalHours:8,availableProductiveHours:40,exclusions:'Não inclui vendas, férias, treinamento ou incidentes não informados. Números didáticos, não benchmark.'};
  a.modelClassification={categories:['managed_automation','oaas'],execution:'Execução de conciliação delimitada pela operação.',acceptance:a.canvas.acceptance,responsibility:'Humano responsável pelas divergências; escopo e remédio a definir.',rationale:'Possível modelo híbrido, sujeito a validar execução, aceite e responsabilidade.'};
  a.resultDefinition={...a.resultDefinition,unit:'Conciliação de uma conta em um período',clockStart:a.canvas.trigger,acceptance:a.canvas.acceptance,exceptions:a.canvas.exceptions,data:a.canvas.inputs,resultLayer:'process'};
  a.experiments=[{id:'demo-experiment-01',hypothesis:'O comprador possui uma dor recorrente, com gasto identificável.',procedure:'Entrevistas exploratórias com roteiro e observação autorizada do processo atual; usar somente dados sintéticos nesta demonstração.',expectedEvidence:'Notas com fonte, período, gasto e responsável pela compra.',responsible:'Responsável fictício',dependencies:['Não utilizar dados pessoais ou privados na demonstração'],period:'Dias 1–15',estimatedCostCents:null,metric:'Gasto atual documentado e comprador identificado',successCriterion:'Registrar evidência suficiente para delimitar a cunha e a linha de base; alvo exploratório, sem validação estatística.',stopRule:'Interromper se o acesso depender de dados ou direitos não autorizados.',status:'planned',safeResearchOnly:true}];
  if(example==='nda'){a.canvas.icp='Pequenas equipes jurídicas — hipótese sintética';a.canvas.sector='Serviços jurídicos';a.canvas.narrow_work='Preparar minuta de NDA para revisão por profissional habilitado';a.canvas.outcome='Rascunho com campos e cláusulas para revisão';a.canvas.acceptance='Profissional responsável verifica adequação e autoriza a versão; nenhum envio automático';a.canvas.human_owner='Profissional habilitado — a identificar';a.canvas.exceptions='Toda minuta requer revisão; o sistema não emite parecer nem assina documentos';a.autonomy.professionalObligation='Revisão profissional e direitos de dados precisam ser definidos antes do piloto';a.economics=null;a.capacity=null;}
  if(example==='provisioning'){a.canvas.icp='Equipes internas de TI — hipótese sintética';a.canvas.sector='Operações de TI';a.canvas.narrow_work='Provisionar usuário de teste em um ambiente isolado';a.canvas.outcome='Conta de teste com permissões mínimas conforme política autorizada';a.canvas.acceptance='Responsável confere identidade, autorização e permissões; registro de auditoria preservado';a.canvas.exceptions='Identidade incerta ou permissão privilegiada exige aprovação competente';a.autonomy.reversibility='Conta de teste revogável; ações reais proibidas na demonstração';a.economics=null;a.capacity=null;}
  return a;
}
