import { describe, expect, it } from 'vitest';
import { assessmentInputSchema, calculateHumanCostCents, compareAssessments, compareSnapshots, createDemoAssessment, createSnapshot, defaultPlan90Days, evaluateAssessment, identifyOperationalSignals, type AssessmentInput } from '../../src/domain/framework';
function comparablePair():[AssessmentInput,AssessmentInput]{const previous=createDemoAssessment();previous.operationalSignals={novelCustomizationPerClient:false,founderDependent:false,onboardingHoursPerClient:4,clientWorkHoursPerAccepted:0.1,qualityMetric:'Taxa de aceite da primeira entrega',qualityValue:0.9,qualityDirection:'higher_better',qualityRubric:'Aceite na primeira apresentação / entregas totais, mesma severidade.',icpMix:'Conciliação fictícia de recebíveis simples',measurementWindow:'mensal',mixComparable:true,comparabilityJustification:'Mesma classe de casos e regra; cliente/coorte diferentes.',evidenceIds:[previous.evidence[0].id],review:{status:'self_declared',author:'Revisor fictício',reviewedAt:'2026-09-23'}};const current=structuredClone(previous);current.economics!.cohort='Coorte sintética B';current.economics!.costs.forEach(c=>{c.cohort='Coorte sintética B';});current.operationalSignals.qualityValue=0.95;return [previous,current];}
describe('comparação de versões e coortes',()=>{
 it('registra diferenças de qualidade, custo e horas por aceito sem comparar scores',()=>{const [a,b]=comparablePair();b.economics!.humanHours=10;b.economics!.costs.find(c=>c.category==='human')!.amountCents=calculateHumanCostCents(10,8000);const r=compareAssessments(a,b);expect(r.comparable).toBe(true);expect(r.metrics.find(m=>m.id==='quality')).toMatchObject({previous:0.9,current:0.95,interpretation:'improved'});expect(r.metrics.find(m=>m.id==='hours_per_accepted')!.delta).toBeCloseTo(-2/90);expect(r.metrics.find(m=>m.id==='cost_per_accepted')!.interpretation).toBe('improved');expect(r).not.toHaveProperty('score');expect(r.limitations.join(' ')).toContain('não comprova causalidade');});
 it('mix diferente suspende deltas e conclusões de melhoria',()=>{const [a,b]=comparablePair();b.operationalSignals.icpMix='Outro mix';const r=compareAssessments(a,b);expect(r.comparable).toBe(false);expect(r.metrics.every(m=>m.delta===null)).toBe(true);expect(r.reasons.join(' ')).toContain('mix');});
 it('declaração de comparabilidade sem revisão e evidência fica pendente',()=>{const [a,b]=comparablePair();b.operationalSignals.review=null;expect(compareAssessments(a,b).comparable).toBe(false);b.operationalSignals.review=a.operationalSignals.review;b.operationalSignals.evidenceIds=['inexistente'];expect(compareAssessments(a,b).comparable).toBe(false);});
 it('qualidade com rubrica diferente continua N/D para comparação, sem ocultar valores',()=>{const [a,b]=comparablePair();b.operationalSignals.qualityRubric='Outra amostragem';const r=compareAssessments(a,b);expect(r.metrics.find(m=>m.id==='quality')).toMatchObject({previous:0.9,current:0.95,delta:null,interpretation:'not_comparable'});expect(r.limitations.join(' ')).toContain('rubrica');});
 it('qualidade com direção menor-melhor interpreta queda corretamente',()=>{const [a,b]=comparablePair();a.operationalSignals.qualityDirection='lower_better';b.operationalSignals.qualityDirection='lower_better';a.operationalSignals.qualityValue=0.1;b.operationalSignals.qualityValue=0.05;expect(compareAssessments(a,b).metrics.find(m=>m.id==='quality')!.interpretation).toBe('improved');});
 it('dados ausentes não viram zero na comparação',()=>{const [a,b]=comparablePair();a.operationalSignals.qualityValue=null;a.economics!.accepted=0;const r=compareAssessments(a,b);expect(r.metrics.find(m=>m.id==='quality')).toMatchObject({previous:null,delta:null,interpretation:'not_available'});expect(r.metrics.find(m=>m.id==='hours_per_accepted')!.previous).toBeNull();});
 it.each(['currency','unit'] as const)('unidades incompatíveis %s não se comparam',(dimension)=>{const [a,b]=comparablePair();b.economics![dimension]=dimension==='currency'?'USD':'documento';b.economics!.costs.forEach(c=>{c[dimension]=b.economics![dimension];});expect(compareAssessments(a,b).comparable).toBe(false);});
 it('janelas mensais e anuais não se comparam diretamente',()=>{const [a,b]=comparablePair();b.operationalSignals.measurementWindow='anual';expect(compareAssessments(a,b).comparable).toBe(false);});
 it('snapshot de regras diferentes preserva original e suspende comparação',()=>{const [a,b]=comparablePair();const first=createSnapshot(a,{id:'a',author:'Owner',createdAt:'2026-09-23T12:00:00Z'});const second=createSnapshot(b,{id:'b',author:'Owner',createdAt:'2026-09-24T12:00:00Z'});const older={...first,rulesVersion:'0.0.9-experimental'};expect(compareSnapshots(older,second).comparable).toBe(false);expect(older.rulesVersion).toBe('0.0.9-experimental');expect(first.rulesVersion).toBe('0.1.0-experimental');});
 it('não compara projetos diferentes',()=>{const [a,b]=comparablePair();b.projectId='different-project';expect(compareAssessments(a,b).comparable).toBe(false);});
});
describe('sinais operacionais sem extrapolação',()=>{
 it('sinaliza customização inédita e dependência do fundador como declarações',()=>{const x=createDemoAssessment();x.operationalSignals.novelCustomizationPerClient=true;x.operationalSignals.founderDependent=true;const signals=identifyOperationalSignals(x);expect(signals.map(s=>s.code)).toEqual(['NOVEL_CUSTOMIZATION_PER_CLIENT','FOUNDER_DEPENDENCY']);expect(signals.every(s=>s.basis==='declared')).toBe(true);expect(evaluateAssessment(x).operationalSignals).toEqual(signals);});
 it('detecta onboarding que não cai e exceções crescentes',()=>{const [a,b]=comparablePair();b.capacity!.exceptionRate=0.3;const codes=identifyOperationalSignals(b,a).map(s=>s.code);expect(codes).toContain('ONBOARDING_NOT_FALLING');expect(codes).toContain('EXCEPTIONS_RISING');});
 it('zero horas de onboarding não gera alerta de não redução',()=>{const [a,b]=comparablePair();a.operationalSignals.onboardingHoursPerClient=0;b.operationalSignals.onboardingHoursPerClient=0;expect(identifyOperationalSignals(b,a).map(s=>s.code)).not.toContain('ONBOARDING_NOT_FALLING');});
 it('crescimento proporcional de trabalho sem margem melhor gera alerta',()=>{const [a,b]=comparablePair();const e=b.economics!;e.completed*=2;e.accepted*=2;e.humanHours!*=2;e.recognizedRevenueCents!*=2;e.receivedRevenueCents!*=2;e.costs.forEach(c=>{c.amountCents!*=2;});const r=compareAssessments(a,b);expect(r.signals.map(s=>s.code)).toContain('PROPORTIONAL_LABOR_WITHOUT_ECONOMIC_IMPROVEMENT');});
 it('ganho de margem não é rotulado como ausência de melhoria econômica',()=>{const [a,b]=comparablePair();const e=b.economics!;e.completed*=2;e.accepted*=2;e.humanHours!*=2;e.recognizedRevenueCents!*=3;e.receivedRevenueCents!*=3;e.costs.forEach(c=>{c.amountCents!*=2;});expect(compareAssessments(a,b).signals.map(s=>s.code)).not.toContain('PROPORTIONAL_LABOR_WITHOUT_ECONOMIC_IMPROVEMENT');});
 it('mostra transferência de trabalho ao cliente, sem atribuir causalidade',()=>{const [a,b]=comparablePair();b.operationalSignals.clientWorkHoursPerAccepted=0.3;expect(compareAssessments(a,b).signals.map(s=>s.code)).toContain('WORK_TRANSFERRED_TO_CLIENT');});
 it('não infere tendências de coortes não comparáveis',()=>{const [a,b]=comparablePair();b.operationalSignals.mixComparable=false;b.capacity!.exceptionRate=0.5;expect(compareAssessments(a,b).signals.filter(s=>s.basis==='calculated_comparison')).toHaveLength(0);});
 it('alertas não alteram peso, pontuação ou trava automaticamente',()=>{const [a,b]=comparablePair();const before=evaluateAssessment(b);b.operationalSignals.founderDependent=true;compareAssessments(a,b);const after=evaluateAssessment(b);expect(after.scorecard).toEqual(before.scorecard);expect(after.decision).toEqual(before.decision);});
});
describe('plano editável e compatibilidade com avaliações antigas',()=>{
 it('dados antigos recebem padrões sem inventar sinais',()=>{const x=createDemoAssessment();const {operationalSignals,plan90Days,...legacy}=x;void operationalSignals;void plan90Days;const parsed=assessmentInputSchema.parse(legacy);expect(parsed.operationalSignals.novelCustomizationPerClient).toBeNull();expect(parsed.operationalSignals.qualityValue).toBeNull();expect(parsed.plan90Days).toHaveLength(5);});
 it('plano de 90 dias pode ser editado sem modificar constante nem outro projeto',()=>{const a=defaultPlan90Days();const b=defaultPlan90Days();a[0].period='Dias 1–25';a[0].responsible='Owner';expect(b[0].period).toBe('Dias 1–15');const x=createDemoAssessment();x.plan90Days=a;const snapshot=createSnapshot(x,{id:'a',author:'Owner',createdAt:'2026-09-23T12:00:00Z'});a[0].objective='Alterado depois';expect(snapshot.input.plan90Days[0].objective).not.toBe('Alterado depois');});
});
